version: "3.9"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_development
    ports:
      - "3306:3306"

  redis:
    image: 'redis:6.2.5'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp' # don't mount tmp directory
    env_file:
      - development.env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    env_file:
      - development.env

volumes:
 db:
 redis: