# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: app_test
          MYSQL_ROOT_PASSWORD: secret
        ports: 
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6.3']

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        mysql --host 127.0.0.1 --port 3306 -u=root -p=secret -e "SHOW GRANTS FOR 'root'@'localhost'"
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port 3306 -u=root -p=secret mysql
        
    - name: Setup Database
      run: bundle exec rake db:setup
      env:
        RAILS_ENV: test
        DB_USER: root
        DB_NAME: app_test
        DB_PASSWORD: secret
        DB_HOST: 0.0.0.0
        DB_PORT: 3306

    - name: Run tests
      run: bundle exec rake
      env:
        RAILS_ENV: test
        DB_USER: root
        DB_NAME: app_test
        DB_PASSWORD: secret
        DB_HOST: 0.0.0.0
        DB_PORT: 3306

